# Generated by Django 4.2.7 on 2023-11-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=80)),
                ('modelYear', models.IntegerField(blank=True, max_length=4, null=True)),
                ('factoryYear', models.IntegerField(blank=True, max_length=4, null=True)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.FloatField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_car', to='Car.marca')),
            ],
        ),
    ]
