# Generated by Django 4.2.7 on 2023-12-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_rename_value_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
