# Generated by Django 4.2.7 on 2023-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
